### PR TITLE
fix: optimize images with next/image

### LINKED ISSUE #28: Optimize Images and large SVGs

### PR DESCRIPTION
**Pull request by acatzk**
Closes #28

### CODE REVIEW

File: src/components/ServiceItem.tsx [hunk 1]
```diff
@@ -9,7 +10,12 @@ import { FunctionComponent } from 'react'
       className="flex flex-col flex-wrap items-center justify-center max-w-md rounded-lg  cursor-default hover:shadow-xl py-8 space-y-6 px-4 transition ease-in-out duration-200"
     >
       <div className="flex-shrink-0">
-        <img src={ icon } className="w-24 md:w-36" />
+        <Image
```
Comment (acatzk) [inline src/components/ServiceItem.tsx:13]: Optmized all image using next/images
